language: python
python:
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get install --only-upgrade openssl # Upgrade OpenSSL to 1.1.1+

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest python-dotenv

script:
  - pytest
